version: '3.9'

networks:
  ms-network:
    driver: bridge

volumes:
  data_mysqldb: null

services:
  mysql-service:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: moview_database
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - data_mysqldb:/var/lib/mysqldb
    networks:
      - ms-network
    tty: true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 1000M
        reservations:
          cpus: "0.50"
          memory: 500M

  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    networks:
      - ms-network
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 500M
        reservations:
          cpus: "0.50"
          memory: 250M
  
  gateway-service:
    build: ./gateway-service
    ports:
      - "8000:8000"
    networks:
      - ms-network
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 500M
        reservations:
          cpus: "0.50"
          memory: 250M
  
  user-service:
    depends_on:
      - mysql-service
    build: ./user-service
    ports:
      - "64412:64412"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ms-network
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 500M
        reservations:
          cpus: "0.50"
          memory: 250M