server:
  port: 8761

spring:
  application:
    name: discovery-service

eureka:
  instance:
    instance-id: discovery-instance
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false